"""
Symbol search — typeahead for stock symbol + name lookup.
GET /api/symbols/search?q=REL   → [{symbol, name}]
GET /api/symbols/quote/{symbol} → {symbol, ltp}
"""

from fastapi import APIRouter, Query

router = APIRouter()

# Static name map — Nifty 50 + high-frequency midcaps
_NAMES: dict[str, str] = {
    "RELIANCE":   "Reliance Industries",
    "TCS":        "Tata Consultancy Services",
    "HDFCBANK":   "HDFC Bank",
    "ICICIBANK":  "ICICI Bank",
    "INFY":       "Infosys",
    "KOTAKBANK":  "Kotak Mahindra Bank",
    "LT":         "Larsen & Toubro",
    "HINDUNILVR": "Hindustan Unilever",
    "ITC":        "ITC Limited",
    "AXISBANK":   "Axis Bank",
    "BAJFINANCE": "Bajaj Finance",
    "BHARTIARTL": "Bharti Airtel",
    "ASIANPAINT": "Asian Paints",
    "MARUTI":     "Maruti Suzuki",
    "WIPRO":      "Wipro",
    "ULTRACEMCO": "UltraTech Cement",
    "TITAN":      "Titan Company",
    "ADANIENT":   "Adani Enterprises",
    "ADANIPORTS": "Adani Ports & SEZ",
    "BAJAJFINSV": "Bajaj Finserv",
    "SBIN":       "State Bank of India",
    "SUNPHARMA":  "Sun Pharmaceutical",
    "TATAMOTORS": "Tata Motors",
    "TATASTEEL":  "Tata Steel",
    "TECHM":      "Tech Mahindra",
    "NESTLEIND":  "Nestle India",
    "NTPC":       "NTPC",
    "POWERGRID":  "Power Grid Corporation",
    "COALINDIA":  "Coal India",
    "HCLTECH":    "HCL Technologies",
    "ONGC":       "Oil & Natural Gas Corp",
    "DRREDDY":    "Dr Reddy's Laboratories",
    "DIVISLAB":   "Divi's Laboratories",
    "CIPLA":      "Cipla",
    "EICHERMOT":  "Eicher Motors",
    "HEROMOTOCO": "Hero MotoCorp",
    "BPCL":       "Bharat Petroleum",
    "JSWSTEEL":   "JSW Steel",
    "BRITANNIA":  "Britannia Industries",
    "APOLLOHOSP": "Apollo Hospitals",
    "HINDALCO":   "Hindalco Industries",
    "M&M":        "Mahindra & Mahindra",
    "INDUSINDBK": "IndusInd Bank",
    "GRASIM":     "Grasim Industries",
    "TATACONSUM": "Tata Consumer Products",
    "SBILIFE":    "SBI Life Insurance",
    "HDFCLIFE":   "HDFC Life Insurance",
    "SHREECEM":   "Shree Cement",
    "BAJAJ-AUTO": "Bajaj Auto",
    "ZOMATO":     "Zomato",
    "PAYTM":      "Paytm (One97 Communications)",
    "NYKAA":      "Nykaa (FSN E-Commerce)",
    "DMART":      "D-Mart (Avenue Supermarts)",
    "SIEMENS":    "Siemens India",
    "PIDILITIND": "Pidilite Industries",
    "HAL":        "Hindustan Aeronautics",
    "HAVELLS":    "Havells India",
    "TRENT":      "Trent",
    "INDIGO":     "IndiGo (InterGlobe Aviation)",
    "ABB":        "ABB India",
    "IRCTC":      "IRCTC",
    "DLF":        "DLF",
    "CHOLAFIN":   "Cholamandalam Investment",
    "PERSISTENT": "Persistent Systems",
    "LTIM":       "LTIMindtree",
    "TATAPOWER":  "Tata Power",
    "ADANIGREEN": "Adani Green Energy",
    "BHEL":       "Bharat Heavy Electricals",
    "GAIL":       "GAIL India",
    "DIXON":      "Dixon Technologies",
    "POLYCAB":    "Polycab India",
    "CGPOWER":    "CG Power & Industrial Solutions",
    "BANKBARODA": "Bank of Baroda",
    "PNB":        "Punjab National Bank",
    "ZEEL":       "Zee Entertainment",
    "JUBLFOOD":   "Jubilant FoodWorks",
    "MUTHOOTFIN": "Muthoot Finance",
    "VEDL":       "Vedanta",
    "LICI":       "LIC India",
    "PFC":        "Power Finance Corporation",
    "RECLTD":     "REC Limited",
    "NHPC":       "NHPC",
    "IRFC":       "Indian Railway Finance Corp",
    "SAIL":       "Steel Authority of India",
    "HINDZINC":   "Hindustan Zinc",
    "NAUKRI":     "Info Edge (Naukri)",
    "ANGELONE":   "Angel One",
    "DEEPAKNTR":  "Deepak Nitrite",
    "GODREJCP":   "Godrej Consumer Products",
    "MARICO":     "Marico",
    "DABUR":      "Dabur India",
    "COLPAL":     "Colgate-Palmolive India",
    "AMBUJACEM":  "Ambuja Cements",
    "GLENMARK":   "Glenmark Pharmaceuticals",
    "IPCALAB":    "IPCA Laboratories",
    "MAXHEALTH":  "Max Healthcare",
    "FORTIS":     "Fortis Healthcare",
    "ALKEM":      "Alkem Laboratories",
    "OBEROIRLTY": "Oberoi Realty",
    "PRESTIGE":   "Prestige Estates",
    "BRIGADE":    "Brigade Enterprises",
    "PHOENIXLTD": "Phoenix Mills",
    "GODREJPROP": "Godrej Properties",
    "LODHA":      "Macrotech Developers (Lodha)",
    "SOBHA":      "Sobha",
    "ASHOKLEY":   "Ashok Leyland",
    "CEATLTD":    "CEAT",
    "ESCORTS":    "Escorts Kubota",
    "BALKRISIND": "Balkrishna Industries",
    "BHARATFORG": "Bharat Forge",
    "MINDA":      "Minda Industries",
    "MOTHERSON":  "Samvardhana Motherson",
    "SONACOMS":   "Sona BLW Precision",
    "AUBANK":     "AU Small Finance Bank",
    "IDFCFIRSTB": "IDFC First Bank",
    "BANDHANBNK": "Bandhan Bank",
    "FEDERALBNK": "Federal Bank",
    "RBLBANK":    "RBL Bank",
    "SBICARD":    "SBI Cards",
    "ICICIGI":    "ICICI Lombard GIC",
    "ICICIPRULI": "ICICI Prudential Life",
    "MANAPPURAM": "Manappuram Finance",
    "LICHSGFIN":  "LIC Housing Finance",
    "M&MFIN":     "Mahindra & Mahindra Financial",
    "PNBHOUSING": "PNB Housing Finance",
    "KFINTECH":   "KFin Technologies",
    "MOTILALOFS": "Motilal Oswal Financial",
    "LTTS":       "L&T Technology Services",
    "OFSS":       "Oracle Financial Services",
    "TATACOMM":   "Tata Communications",
    "INDIAMART":  "IndiaMart InterMESH",
    "MCX":        "MCX India",
    "IEX":        "Indian Energy Exchange",
    "BSE":        "BSE Limited",
    "TATATECH":   "Tata Technologies",
    "KPITTECH":   "KPIT Technologies",
    "HAPPSTMNDS": "Happiest Minds",
    "MPHASIS":    "Mphasis",
    "COFORGE":    "Coforge",
    "VOLTAS":     "Voltas",
    "BLUESTARCO": "Blue Star",
    "CROMPTON":   "Crompton Greaves Consumer",
    "VGUARD":     "V-Guard Industries",
    "TORNTPOWER": "Torrent Power",
    "ADANIGAS":   "Adani Total Gas",
    "PETRONET":   "Petronet LNG",
    "GUJGASLTD":  "Gujarat Gas",
    "GSPL":       "Gujarat State Petronet",
    "ATGL":       "Adani Total Gas",
    "RAMCOCEM":   "Ramco Cements",
    "JKCEMENT":   "JK Cement",
    "DALBHARAT":  "Dalmia Bharat",
    "TATACHEM":   "Tata Chemicals",
    "ATUL":       "Atul Limited",
    "NAVINFLUOR": "Navin Fluorine",
    "VINATIORGA": "Vinati Organics",
    "CLEAN":      "Clean Science & Technology",
    "FLUOROCHEM": "Gujarat Fluorochemicals",
    "NOCIL":      "NOCIL",
    "LALPATHLAB": "Dr Lal PathLabs",
    "METROPOLIS": "Metropolis Healthcare",
    "AJANTPHARM": "Ajanta Pharma",
    "ABBOTINDIA": "Abbott India",
    "PFIZER":     "Pfizer India",
    "NEULAND":    "Neuland Laboratories",
    "PAGEIND":    "Page Industries",
    "RAYMOND":    "Raymond",
    "CAMPUS":     "Campus Activewear",
    "MANYAVAR":   "Vedant Fashions (Manyavar)",
    "SAFARI":     "Safari Industries",
    "EASEMYTRIP": "EaseMyTrip",
    "NAZARA":     "Nazara Technologies",
    "UJJIVANSFB": "Ujjivan Small Finance Bank",
    "EQUITASBNK": "Equitas Small Finance Bank",
    "HUDCO":      "HUDCO",
    "SJVN":       "SJVN",
    "RVNL":       "Rail Vikas Nigam",
    "IRCON":      "Ircon International",
    "NBCC":       "NBCC India",
    "RITES":      "RITES",
    "RAILTEL":    "RailTel Corporation",
    "CONCOR":     "Container Corporation",
    "APLAPOLLO":  "APL Apollo Tubes",
    "RATNAMANI":  "Ratnamani Metals",
    "TITAGARH":   "Titagarh Rail Systems",
    "BHEL":       "Bharat Heavy Electricals",
    "CUMMINSIND": "Cummins India",
    "THERMAX":    "Thermax",
    "ELGIEQUIP":  "Elgi Equipments",
    "GRINDWELL":  "Grindwell Norton",
    "SKFINDIA":   "SKF India",
    "TIMKEN":     "Timken India",
    "KALPATPOWR": "Kalpataru Power",
    "KNRCON":     "KNR Constructions",
    "IRB":        "IRB Infrastructure",
    "SUNTV":      "Sun TV Network",
    "PVR":        "PVR Inox",
    "SAREGAMA":   "Saregama India",
    "RADICO":     "Radico Khaitan",
    "MCDOWELL-N": "United Spirits",
    "VBL":        "Varun Beverages",
    "UNITEDBRW":  "United Breweries",
    "BATA":       "Bata India",
    "RELAXO":     "Relaxo Footwears",
    "DEVYANI":    "Devyani International",
    "SAPPHIRE":   "Sapphire Foods",
    "VSTIND":     "VST Industries",
    "HFCL":       "HFCL",
    "TATAELXSI":  "Tata Elxsi",
    "MASTEK":     "Mastek",
    "ZENSARTECH": "Zensar Technologies",
    "TANLA":      "Tanla Platforms",
    "JINDALSTEL": "Jindal Steel & Power",
    "NATIONALUM": "National Aluminium",
    "WELSPUNIND": "Welspun India",
    "SUPREMEIND": "Supreme Industries",
    "ASTRAL":     "Astral",
    "PRINCEPIPE": "Prince Pipes",
    "FINOLEX":    "Finolex Industries",
    "BAJAJHLDNG": "Bajaj Holdings",
    "NAM-INDIA":  "Nippon India Mutual Fund",
    "UTIAMC":     "UTI AMC",
    "IIFL":       "IIFL Finance",
    "CREDITACC":  "CreditAccess Grameen",
    "FINEORG":    "Fine Organic Industries",
    "BALAMINES":  "Balaji Amines",
    "KARURVYSYA": "Karur Vysya Bank",
    "CITYUNIONB": "City Union Bank",
    "DCBBANK":    "DCB Bank",
    "UNIONBANK":  "Union Bank of India",
    "IOB":        "Indian Overseas Bank",
    "CANBK":      "Canara Bank",
    "HEXAWARE":   "Hexaware Technologies",
    "BOSCHLTD":   "Bosch",
    "BERGEPAINT": "Berger Paints",
    "POLICYBZR":  "PB Fintech (Policybazaar)",
    "TORNTPHARM": "Torrent Pharmaceuticals",
    "TATACONSUM": "Tata Consumer Products",
    "AIAENG":     "AIA Engineering",
    "WHIRLPOOL":  "Whirlpool of India",
    "HONAUT":     "Honeywell Automation",
    "STAR":       "Star Health Insurance",
    "SCI":        "Shipping Corporation of India",
    "TCI":        "TCI Express",
    "KPRMILL":    "KPR Mill",
    "JUBLPHARMA": "Jubilant Pharmova",
    "GLOBUS":     "Globus Spirits",
    "BSOFT":      "BIRLASOFT",
    "NIITTECH":   "Coforge (formerly NIIT Tech)",
}


@router.get("/search")
def search_symbols(q: str = Query(default="", min_length=1, max_length=30)):
    """Typeahead — matches symbol prefix or company name substring. Returns up to 15 results."""
    from src.market.universe import NIFTY_500

    q_upper = q.upper().strip()
    if not q_upper:
        return {"results": []}

    results: list[dict] = []
    # Prioritise symbol prefix matches, then name matches
    prefix_hits, name_hits = [], []

    for sym in NIFTY_500:
        name = _NAMES.get(sym, sym)
        if sym.startswith(q_upper):
            prefix_hits.append({"symbol": sym, "name": name})
        elif q_upper in sym or q_upper in name.upper():
            name_hits.append({"symbol": sym, "name": name})

    results = prefix_hits + name_hits
    return {"results": results[:15]}


@router.get("/quote/{symbol}")
def live_quote(symbol: str):
    """Current LTP for a symbol via yfinance (thin wrapper, no SSE)."""
    from src.api.routers.orders import _get_ltp
    sym = symbol.upper().strip()
    ltp = _get_ltp(sym)
    name = _NAMES.get(sym, sym)
    return {"symbol": sym, "name": name, "ltp": round(ltp, 2) if ltp else None}
